### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Cerabbite** [Lycoon/scriptio#53]
![image](https://user-images.githubusercontent.com/98265679/217638336-be9e6193-a009-4fd3-ae65-3beff14c224c.png)

**Comment by Cerabbite** [comment]
For some more context. I already saw it this morning (about 12/13 hours ago) thinking my login session was expired or something. But right now I wanted to get some writing done, and I went to scriptio.io, and I still got a 502 error. The image is from Chrome and I also tested in Brave with the same result.

**Comment by Lycoon** [comment]
You're totally right. I'm planning to move Scriptio on a better hosting service someday as the current one is very unstable. The project is still in beta and these crashes will occur until I don't release it explicitly. The uptime for https://scriptio.app/ is clearly not my priority right now, it's better to pull current repository and test locally 👍
