### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ad-si** [Lycoon/scriptio#58]

**Comment by Lycoon** [comment]
Hi Adrian,

First, thank you for using Scriptio 😁 I've been pausing Scriptio development recently for personal reasons and forgot about switching on a better server machine. I'm planning to do it asap. The thing is, I'm still developing it and can't guarantee its uptime for now, here is a [related issue](https://github.com/Lycoon/scriptio/issues/53#issuecomment-1423251131).

I'll reboot the machine this evening and advise you to test it locally until it officially releases!

**Comment by ad-si** [comment]
Cool, a really nice, focused app! Looking forward to where you'll take it! 😊
